### PR TITLE
make seekbar better

### PR DESCRIPTION
**Pull request by yofukashino**
made the seek bar better by using Discord's slider component and adjusted the style according to it

also added a check in the plaintext patch as sometimes it requires the code before plugin has started and set exports

### CODE REVIEW

**Comment by Socketlike** [comment]
Have you actually tested any of this?

**Comment by yofukashino** [comment]
I am using it rn and it's working

**Comment by yofukashino** [comment]
spotify
see

**Comment by Socketlike** [comment]
> spotify
> see

Can the padding between the song timestamps and the seekbar be any lesser than that?

Also the seekbar isn't wide enough to cover the whole modal.

**Comment by yofukashino** [comment]
That's the default. With css I can try maybe

**Comment by Socketlike** [comment]
> That's the default. With css I can try maybe 

Please test this with `replugged.plugins.getExports("lib.evelyn.SpotifyModal").events.on("message", (data) => console.log(data.detail))` and see how many WebSocket messages you receive after you seek using the seekbar.

I personally don't trust Discord's slider. (It fires its `onChange` way too much in my experience)

**Comment by yofukashino** [comment]
image
fixed the padding

about it firing more than once, set a const such as isUpdating and then make it true while its updating, and if another request comes while its updating, just dont process that one. will be good for not making too many request too


edit it fires twice sometimes

**Pull request merged**
